services:
  - type: web
    name: pinterest-scraper
    runtime: docker # Changed from node to docker
    plan: free
    dockerfilePath: ./pinterst-scraper/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: WALLPAPER_PIPELINE_URL
        value: https://wallpaper-pipeline.onrender.com
      - key: NODE_ENV
        value: production